"""
Django settings for dev project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from decouple import config,Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apis'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'dev.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST':config("DB_HOST"),
        'PORT':config("DB_PORT"),
        'USER':config("DB_USER"),
        'PASSWORD':config("DB_PASSWORD"),
        'NAME':config("DB_NAME"),
        'OPTIONS': {
            'init_command':"SET sql_mode='STRICT_TRANS_TABLES'"
        },
        'TEST_CHARSET': 'utf8',
        'TEST_COLLATION': 'utf8_general_ci',

    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = config("LANGUAGE_CODE")

TIME_ZONE = config("TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 🔍 LOGGING Configuration - Cache Debug & Performance Monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'apis.entities.models.EntityModels': {
            'handlers': ['console'],
            'level': 'INFO',  # Cambiar a 'DEBUG' para logs más detallados
            'propagate': False,
        },
        'apis.services.entrysresults': {
            'handlers': ['console'],
            'level': 'INFO',  # Cambiar a 'DEBUG' para logs más detallados
            'propagate': False,
        },
        'apis.services.cronjobs': {
            'handlers': ['console'],
            'level': 'INFO',  # Cambiar a 'DEBUG' para logs más detallados
            'propagate': False,
        },
        'apis.services.entrys': {
            'handlers': ['console'],
            'level': 'INFO',  # Cambiar a 'DEBUG' para logs más detallados
            'propagate': False,
        },
        'apis.services.events': {
            'handlers': ['console'],
            'level': 'INFO',  # Cambiar a 'DEBUG' para logs más detallados
            'propagate': False,
        },
        'apis.services.managerdays': {
            'handlers': ['console'],
            'level': 'INFO',  # WARNING para solo ver problemas
            'propagate': False,
        },
        'apis.services.checkpinbar': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrends': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsrecent': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsrecentml': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsml': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsexpansive': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsexpansiveml': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsexpansiverecent': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsexpansiverecentml': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsminus': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsminusrecent': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsminusrecentml': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checkenvolvent': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checkenvolventml': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checkpinbarml': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checktrendsminusml': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checkwma': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checkwmarecent': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checkwmarecentml': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.services.checkwmaml': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
